rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - ruby-head

script: "bundle exec rake spec"

before_script:
  - mysql -e 'create database perfectqueue_test;'

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  webhooks: http://td-beda.herokuapp.com/travisci_callback
