# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{perfectqueue}
  s.version = "0.7.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sadayuki Furuhashi"]
  s.date = %q{2011-09-16}
  s.default_executable = %q{perfectqueue}
  s.email = %q{frsyuki@gmail.com}
  s.executables = ["perfectqueue"]
  s.extra_rdoc_files = [
    "ChangeLog",
     "README.rdoc"
  ]
  s.files = [
    "bin/perfectqueue",
     "lib/perfectqueue.rb",
     "lib/perfectqueue/backend.rb",
     "lib/perfectqueue/backend/rdb.rb",
     "lib/perfectqueue/backend/simpledb.rb",
     "lib/perfectqueue/command/perfectqueue.rb",
     "lib/perfectqueue/engine.rb",
     "lib/perfectqueue/version.rb",
     "lib/perfectqueue/worker.rb"
  ]
  s.homepage = %q{https://github.com/treasure-data/perfectqueue}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Highly available distributed queue built on RDBMS or SimpleDB}
  s.test_files = [
    "test/backend_test.rb",
     "test/exec_test.rb",
     "test/test_helper.rb",
     "test/cat.sh",
     "test/echo.sh",
     "test/fail.sh",
     "test/huge.sh",
     "test/success.sh"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sequel>, ["~> 3.26.0"])
      s.add_runtime_dependency(%q<aws-sdk>, ["~> 1.1.1"])
    else
      s.add_dependency(%q<sequel>, ["~> 3.26.0"])
      s.add_dependency(%q<aws-sdk>, ["~> 1.1.1"])
    end
  else
    s.add_dependency(%q<sequel>, ["~> 3.26.0"])
    s.add_dependency(%q<aws-sdk>, ["~> 1.1.1"])
  end
end

